# For local development
# Make sure when creating the environment you have installed conda
# conda env create -f *Name of This File (ex. requirements.yaml)*
# Select "install ikernel" when popup appears when first activating running a cell in an .ipynb file with the env
# Use: "conda activate *Name of Env (ex. my_env)*" when running scripts in the terminal to activate the environment

name: sa_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip=25.3
  - fsspec=2026.1.0
  - ipykernel=6.31.0
  - ipywidgets=8.1.8
  - numpy>=2.41.1
  - pandas>=2.3.3
  - pytorch=2.8.0
  - pytorch-cuda=12.4
  - scikit-learn=1.8.0
  - seaborn=0.13.2
  - tqdm=4.67.1
  - pip:
    - sagemaker==3.3.1